apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: shashankbarsin/azure-pipelines-k8s-canarydemo
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
